name=PropertiesConfigLog4j2

appenders=console

appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%level] %d{dd-MM-yyyy HH:mm:ss} [%t] %c{1} - %msg%n

rootLogger.level=info
rootLogger.appenderRefs=stdout
rootLogger.appenderRef.stdout.ref=STDOUT
#Hi?n t?i m?i ch? c?n ghi console log ?? in log trên ch? console t?m th?i debug thôi. \
#  Sau ni khi build xong ch?y ?n ??nh m?i thêm c?u hình file log ?? cho 1 file ghi l?i ti?n trình ch?y luôn